# Generated by Django 4.2.7 on 2023-11-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cfdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journail_id', models.IntegerField(blank=True, null=True)),
                ('currendy_id', models.IntegerField(blank=True, null=True)),
                ('payment_method_id', models.IntegerField(blank=True, null=True)),
                ('estado_pago', models.CharField(blank=True, max_length=250, null=True)),
                ('forma_pago', models.CharField(max_length=500)),
                ('payment_type', models.CharField(blank=True, max_length=500, null=True)),
                ('tipocambio', models.FloatField(blank=True, null=True)),
                ('total_factura', models.FloatField(blank=True, null=True)),
                ('tax_payment', models.TextField(max_length=500)),
                ('monedaDR', models.CharField(max_length=500)),
                ('equivalenciaDR', models.CharField(max_length=500)),
                ('folio_facura', models.CharField(max_length=500)),
                ('IdDocumento', models.CharField(max_length=500)),
                ('numParcialidad', models.CharField(max_length=500)),
                ('ImpSaldoAnt', models.FloatField(blank=True, null=True)),
                ('ImpPagado', models.FloatField(blank=True, null=True)),
                ('ImpSaldoInsoluto', models.FloatField(blank=True, null=True)),
                ('ObjetoImpDr', models.CharField(max_length=500)),
                ('ImpuestoDR', models.TextField()),
                ('factura_cfdi', models.BooleanField(blank=True, null=True)),
                ('monto_pagado', models.FloatField(blank=True, null=True)),
                ('payment_content', models.TextField()),
            ],
            options={
                'db_table': 'cfdi',
            },
        ),
    ]
